=== apache/incubator-retired-tamaya/core/src/main/resources/META-INF/java-config-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy current the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://java-config.java.net/metamodel/1.0.0"
        xmlns:tns="http://java-config.java.net/metamodel/1.0.0"
        elementFormDefault="qualified">

    <element name="java-config">
        <complexType>
            <sequence>
                <element name="metaModel" minOccurs="1" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="configParts">
                                <complexType>
                                    <sequence>
                                        <element name="configPart" type="tns:configPart" maxOccurs="unbounded"/>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" type="string"></attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="configPart">
        <sequence>
            <sequence>
                <element name="properties" type="tns:properties"></element>
            </sequence>
            <sequence>
                <element name="childParts" type="tns:childParts"></element>
            </sequence>
        </sequence>
        <attribute name="key" type="string"></attribute>
        <attribute name="partType" type="string"></attribute>
        <attribute name="propertyMapSpec" type="string"></attribute>
    </complexType>

    <complexType name="properties">
        <sequence>
            <element name="comment" type="tns:entry"></element>
            <element name="entry" type="tns:entry"></element>
        </sequence>
    </complexType>
    <complexType name="entry">
        <attribute name="key" type="string"></attribute>
    </complexType>

    <complexType name="childParts">
        <sequence>
            <element name="childPart" type="tns:entry">
                <complexType>
                    <attribute name="psrtType" type="string"></attribute>
                    <attribute name="keyRef" type="string"></attribute>
                </complexType>
            </element>
        </sequence>
    </complexType>

</schema>

=== apache/incubator-retired-tamaya/core/src/main/resources/META-INF/java-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy current the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<java-config xmlns="http://java.net/projects/javaconfig/java-config/1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="java-config-1.0.0.xsd">
    <metaModel id="default">
       <configParts>
           <configPart key="sys-properties" partType="javax.config.PropertyMap" propertyMapSpec="org.apache.tamaya.core.properties.SystemPropertiesPropertyMap"/>
           <configPart key="env-properties" partType="javax.config.PropertyMap" propertyMapSpec="org.apache.tamaya.core.properties.EnvironmentPropertyMap"/>
           <configPart key="--system--" partType="org.apache.tamaya.Configuration" propertyMapSpec="union">
               <childPart partType="javax.config.PropertyMap" keyRef="sys-properties"/>
               <childPart partType="javax.config.PropertyMap" keyRef="env-properties"/>
           </configPart>
       </configParts>
    </metaModel>
</java-config>
